import {
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiClose,
  mdiTune,
  mdiMinus,
  mdiPlus,
  mdiCheck,
  mdiFire,
  mdiChartArc,
  mdiCog,
  mdiCarBrakeAlert,
  mdiPrinter3d,
  mdiPrinter3dNozzle,
  mdiPrinter3dNozzleOutline,
  mdiFileCodeOutline,
  mdiFileRefreshOutline,
  mdiConsole,
  mdiChevronUp,
  mdiChevronDown,
  mdiLightningBoltCircle,
  mdiCloudArrowDownOutline,
  mdiChevronTripleDown,
  mdiChevronTripleUp,
  mdiTimerSand,
  mdiClockOutline,
  mdiFormatLineSpacing,
  mdiPause,
  mdiWindowClose,
  mdiPrinter,
  mdiCamera,
  mdiFan,
  mdiArrowUp,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowCollapseDown,
  mdiArrowCollapseHorizontal,
  mdiViewGridOutline,
  mdiArrowExpandHorizontal,
  mdiArrowExpandVertical,
  mdiRefresh,
  mdiCheckCircleOutline,
  mdiCheckboxBlankCircleOutline,
  mdiPrinter3dNozzleAlertOutline,
  mdiAlertCircle,
  mdiFolderPlus,
  mdiFile,
  mdiFileLock,
  mdiFolder,
  mdiFolderLock,
  mdiPencil,
  mdiMagnify,
  mdiMagnifyPlus,
  mdiMagnifyMinus,
  mdiDownload,
  mdiFormTextbox,
  mdiDelete,
  mdiCogs,
  mdiContentSaveOutline,
  mdiAlert,
  mdiDotsVertical,
  mdiSend,
  mdiArrowHorizontalLock,
  mdiChartTimelineVariant,
  mdiFireAlert,
  mdiSnowflakeAlert,
  mdiUpload,
  mdiFolderUpload,
  mdiProgressUpload,
  mdiProgressQuestion,
  mdiRadioboxMarked,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarkedOutline,
  mdiFilePlus,
  mdiBellOutline,
  mdiPower,
  mdiPowerCycle,
  mdiRestart,
  mdiRestartAlert,
  mdiUpdate,
  mdiChevronRight,
  mdiChevronLeft,
  mdiDrag,
  mdiCheckboxMultipleBlank,
  mdiOpenInApp,
  mdiDesktopTower,
  mdiDotsHorizontal,
  mdiToggleSwitch,
  mdiToggleSwitchOffOutline,
  mdiMotionOutline,
  mdiThermometerLow,
  mdiHelpCircle,
  mdiHistory,
  mdiFilterOutline,
  mdiSourceCommit,
  mdiArrowExpandUp,
  mdiCloudCheck,
  mdiCloudAlert,
  mdiCircle,
  mdiFolderMove,
  mdiConsoleLine,
  mdiDotsGrid,
  mdiHammerWrench,
  mdiAccount,
  mdiFileTableOutline,
  mdiLock,
  mdiLockOpenVariant,
  mdiPencilLock,
  mdiLockReset,
  mdiCubeScan,
  mdiHandBackRight,
  mdiThermometerAlert,
  mdiShieldAccount,
  mdiContentCopy,
  mdiApps,
  mdiAccountPlus,
  mdiViewDashboardOutline,
  mdiHome,
  mdiRestore,
  mdiMenu,
  mdiFileCancel,
  mdiCancel,
  mdiCircleSlice3,
  mdiCodeJson,
  mdiHarddisk,
  mdiLayersTripleOutline,
  mdiMessageTextOutline,
  mdiFormatListBulleted,
  mdiSwapVertical,
  mdiFullscreen,
  mdiStop,
  mdiPlay,
  mdiFileVideoOutline,
  mdiBellSleep,
  mdiChip,
  mdiViewHeadline,
  mdiAxisArrow,
  mdiVectorLine,
  mdiOpenInNew,
  mdiImageSizeSelectLarge,
  mdiListStatus,
  mdiLayersMinus,
  mdiLayers,
  mdiLayersPlus,
  mdiFolderOpen,
  mdiArchive,
  mdiArchivePlus,
  mdiTrayFull,
  mdiTrayPlus,
  mdiFolderArrowUp,
  mdiTableColumn,
  mdiShape,
  mdiSync,
  mdiContentDuplicate,
  mdiArchiveLock,
  mdiFileImage,
  mdiGauge,
  mdiMonitorScreenshot,
  mdiRotateLeft,
  mdiRotateRight,
  mdiToothbrush,
  mdiVacuum,
  mdiSpeedometer,
  mdiWaves,
  mdiReload,
  mdiArrowULeftTop,
  mdiOneUp,
  mdiHeart,
  mdiPlaylistMusic,
  mdiGamepadVariant,
  mdiRewind,
  mdiFastForward,
  mdiVolumeHigh,
  mdiVolumeMedium,
  mdiVolumeLow,
  mdiVolumeOff,
  mdiShare,
  mdiMusicNotePlus
} from '@mdi/js'

export const Icons = Object.freeze({
  dash: mdiViewDashboardOutline,
  account: mdiAccount,
  addAccount: mdiAccountPlus,
  help: mdiHelpCircle,
  motion: mdiMotionOutline,
  limits: mdiArrowHorizontalLock,
  send: mdiSend,
  open: mdiOpenInApp,
  move: mdiFolderMove,
  reload: mdiReload,
  restore: mdiRestore,
  tabs: mdiCheckboxMultipleBlank,
  menu: mdiDotsVertical,
  menuAlt: mdiMenu,
  dots: mdiDotsHorizontal,
  dotsGrid: mdiDotsGrid,
  drag: mdiDrag,
  chart: mdiChartTimelineVariant,
  power: mdiPower,
  powerCycle: mdiPowerCycle,
  powerOn: mdiToggleSwitch,
  powerOff: mdiToggleSwitchOffOutline,
  home: mdiHome,
  close: mdiClose,
  refresh: mdiRefresh,
  restart: mdiRestart,
  restartAlert: mdiRestartAlert,
  update: mdiUpdate,
  warning: mdiAlert,
  error: mdiHandBackRight,
  thermometer: mdiThermometerLow,
  bell: mdiBellOutline,
  fireAlert: mdiFireAlert,
  snowflakeAlert: mdiSnowflakeAlert,
  circle: mdiCircle,
  vacuum: mdiVacuum,
  blankCircle: mdiCheckboxBlankCircleOutline,
  markedCircle: mdiRadioboxMarked,
  checkedCircle: mdiCheckCircleOutline,
  checkboxBlank: mdiCheckboxBlankOutline,
  checkboxMarked: mdiCheckboxMarkedOutline,
  arcLightning: mdiLightningBoltCircle,
  gasCloud: mdiCloudArrowDownOutline,
  wireUp: mdiChevronTripleUp,
  wireDown: mdiChevronTripleDown,
  alertCircle: mdiAlertCircle,
  folderAdd: mdiFolderPlus,
  folderUp: mdiFolderUpload,
  folderUpload: mdiFolderArrowUp,
  folder: mdiFolder,
  folderLock: mdiFolderLock,
  fileUpload: mdiUpload,
  fileAdd: mdiFilePlus,
  inProgress: mdiCircleSlice3,
  progressUpload: mdiProgressUpload,
  progressQuestion: mdiProgressQuestion,
  up: mdiArrowUp,
  down: mdiArrowDown,
  left: mdiArrowLeft,
  right: mdiArrowRight,
  tune: mdiTune,
  zUp: mdiArrowExpandUp,
  zDown: mdiArrowCollapseDown,
  zeroPosition: mdiArrowCollapseHorizontal,
  expandHorizontal: mdiArrowExpandHorizontal,
  expandVertical: mdiArrowExpandVertical,
  cog: mdiCog,
  cogs: mdiCogs,
  save: mdiContentSaveOutline,
  estop: mdiCarBrakeAlert,
  fire: mdiFire,
  chartArc: mdiChartArc,
  tools: mdiHammerWrench,
  minus: mdiMinus,
  plus: mdiPlus,
  check: mdiCheck,
  console: mdiConsole,
  clock: mdiClockOutline,
  undo: mdiArrowULeftTop,
  formatLineSpacing: mdiFormatLineSpacing,
  layersTripleOutline: mdiLayersTripleOutline,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  chevronRight: mdiChevronRight,
  chevronLeft: mdiChevronLeft,
  chevronDoubleLeft: mdiChevronDoubleLeft,
  chevronDoubleRight: mdiChevronDoubleRight,
  timer: mdiTimerSand,
  fileCode: mdiFileCodeOutline,
  fileRefresh: mdiFileRefreshOutline,
  files: mdiFileTableOutline,
  file: mdiFile,
  fileLock: mdiFileLock,
  fileCancel: mdiFileCancel,
  pause: mdiPause,
  cancel: mdiWindowClose,
  cancelled: mdiCancel,
  play: mdiPlay,
  resume: mdiPlay,
  stop: mdiStop,
  reprint: mdiPrinter,
  printer: mdiPrinter,
  download: mdiDownload,
  rename: mdiFormTextbox,
  duplicate: mdiContentDuplicate,
  sync: mdiSync,
  delete: mdiDelete,
  camera: mdiCamera,
  fan: mdiFan,
  pencil: mdiPencil,
  pencilLock: mdiPencilLock,
  magnify: mdiMagnify,
  magnifyPlus: mdiMagnifyPlus,
  magnifyMinus: mdiMagnifyMinus,
  printer3d: mdiPrinter3d,
  printer3dNozzle: mdiPrinter3dNozzleOutline,
  printer3dNozzleAlert: mdiPrinter3dNozzleAlertOutline,
  waves: mdiWaves,
  speedometer: mdiSpeedometer,
  bedMesh: mdiViewGridOutline,
  host: mdiDesktopTower,
  history: mdiHistory,
  filter: mdiFilterOutline,
  commit: mdiSourceCommit,
  cloudCheck: mdiCloudCheck,
  cloudAlert: mdiCloudAlert,
  cubeScan: mdiCubeScan,
  consoleLine: mdiConsoleLine,
  lock: mdiLock,
  lockOpen: mdiLockOpenVariant,
  lockReset: mdiLockReset,
  reset: mdiRestore,
  tempError: mdiThermometerAlert,
  contentCopy: mdiContentCopy,
  apps: mdiApps,
  shieldAccount: mdiShieldAccount,
  retract: mdiSwapVertical,
  codeJson: mdiCodeJson,
  desktopTower: mdiDesktopTower,
  harddisk: mdiHarddisk,
  message: mdiMessageTextOutline,
  list: mdiFormatListBulleted,
  fullScreen: mdiFullscreen,
  video: mdiFileVideoOutline,
  snooze: mdiBellSleep,
  chip: mdiChip,
  viewHeadline: mdiViewHeadline,
  absolutePositioning: mdiAxisArrow,
  relativePositioning: mdiVectorLine,
  openInNew: mdiOpenInNew,
  imageSizeSelectLarge: mdiImageSizeSelectLarge,
  listStatus: mdiListStatus,
  previousLayer: mdiLayersMinus,
  currentLayer: mdiLayers,
  nextLayer: mdiLayersPlus,
  moves: mdiVectorLine,
  extrusions: mdiPrinter3dNozzle,
  retractions: mdiSwapVertical,
  tableColumn: mdiTableColumn,
  parts: mdiShape,
  folderOpen: mdiFolderOpen,
  fileImage: mdiFileImage,
  fileZip: mdiArchive,
  fileZipLock: mdiArchiveLock,
  fileZipAdd: mdiArchivePlus,
  cleanNozzle: mdiToothbrush,
  jobQueue: mdiTrayFull,
  enqueueJob: mdiTrayPlus,
  sensors: mdiGauge,
  screenshot: mdiMonitorScreenshot,
  zRotateClockwise: mdiRotateRight,
  zRotateCounterclockwise: mdiRotateLeft,
  mushroom: mdiOneUp,
  heart: mdiHeart,
  gamepad: mdiGamepadVariant,
  playlist: mdiPlaylistMusic,
  rewind: mdiRewind,
  fastForward: mdiFastForward,
  volumeHigh: mdiVolumeHigh,
  volumeMedium: mdiVolumeMedium,
  volumeLow: mdiVolumeLow,
  volumeOff: mdiVolumeOff,
  share: mdiShare,
  addMusic: mdiMusicNotePlus
})
